### ISSUE TITLE
Require JWTs for requests in production

### ISSUE THREAD

**Issue by ericgio** [yekrojam/api#21]
JWTs add a layer of security to the API and allow per-request authentication. Based on what I've learned, it would work as follows:

- For every request, the API requires a valid token from the client. The token is generated using a secret shared by the client(s) and server. When the server receives a request, it decodes the token using the secret.
- The contents of the token can be empty, eg: for logged out requests. Logged-in requests will include some unique identifier like an id or auth string that can be used to validate permissions, eg: if a user is trying to mutate an object.
- Each client will need to implement generating and sending the token with each request.

**Comment by makinde** [comment]
#38 addresses this

**Comment by ericgio** [comment]
Added in #44
