### ISSUE TITLE
Save birthday as a date string instead of separate fields

### ISSUE THREAD

**Issue by ericgio** [yekrojam/api#33]
We discussed this briefly and IIRC your rationale was that splitting it up allowed the user to control privacy. A few arguments in favor of combining:

- Much simpler from a data perspective: fewer fields in the schema, easier to validate (just pass into Moment), easier to use, eg: with a datepicker component on the client.
- Given age-related privacy and data laws, it's common for apps to request full birthdate info. Display settings should be left to the client.

**Comment by makinde** [comment]
Yeah, two question here. 

1) What model should be presented to the user (date picker, asking for full birthday - vs- asking for year separately from month/day. I think you're right that there's a lot of reason to model it to the user as the former

2) How data is stored.

You should feel free to present things to the user as a date picker.

One way I can make this easier is to create a virtual that allows you to get/set `fullBirthday` (or something) via querying/setting the field like this: `{ fullBirthday: '1994-09-21' }`. You could then ignore the 3 specific fields and imagine they don't exist from a client perspective. Would that work?

**Comment by ericgio** [comment]
Yes, my main concern here was how the data is stored. Client should just do whatever it wants. A virtual works in the short-term, though this is not blocking anything so I was mainly creating the issue for discussion and where we want to end up longer-term.

**Comment by makinde** [comment]
Yeah, this isn't a change I'm really interested in making. There's a feature I want to build the depends on year being optional and month/day being optional. And I want to API to support that. The alternative implementation for optional year would be to store the year in one field and the month/day in another field, which seems worse.

Thankfully, this is deep enough in the API that if we decide to change it later, it's pretty easy and the client doesn't need to know.

**Comment by ericgio** [comment]
What's the feature? Seems fine for this to be a wontfix for now.

**Comment by makinde** [comment]
month/date being optional
